add color on button
vlang/ui pull request #261
Opened 2021-01-01 21:29 UTC by enghitalo

2021-01-01 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vlang/ui?pullRequest=261) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vlang/ui?pullRequest=261) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vlang/ui?pullRequest=261) it.</sub>

2021-01-01 21:37 UTC, serkonda7 requested changes
What happens if you not set an color?

2021-01-01 22:09 UTC, enghitalo commented
> What happens if you not set an color?

The button will be white

2021-01-01 22:25 UTC, serkonda7 approved these changes

2021-02-19 19:55 UTC, serkonda7 commented
Closing this in favor of upcoming theming support

2021-02-19 19:55 UTC, closed without merging